print("--------------------------------------BANK MANAGEMENT SYSTEM-------------------------------------------------")
print("1. Create Account")
print("2. Update Account")
print("3. Delete Account")
print("4. Check Account")
print("5. Balance Account")
print("6. Withdrawn Account")
print("7. Total Balance Account")
print("8. Closing THE BANKING APP...\nThank You!")
